Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      ImageId: ami-0953476d60561c955  # Replace with your region-specific AMI ID
      Tags:
        - Key: Name
          Value: MyEC2